plugins {
    id 'io.freefair.lombok' version '8.14'
    id 'com.adarshr.test-logger' version '4.0.0'
}

ext {
    springBootVersion = '4.1.1'
    springDepMgmtVersion = '1.1.7'
    junitVersion = '5.11.4'
    nettyVersion = '4.2.17.Final'
    slf4jVersion = '2.0.17'
    logbackVersion = '1.5.18'
    jnaVersion = '5.16.0'
    jmdnsVersion = '3.6.0'
    plistVersion = '1.28'
    eddsaVersion = '0.3.0'
    curve25519Version = '0.5.0'
    gstreamerCoreVersion = '1.4.0'
    gstreamerSwingVersion = '0.9.0'
}

allprojects {
    apply plugin: 'java'

    group 'com.github.serezhka'
    version '1.0.7'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'io.freefair.lombok'
    apply plugin: 'com.adarshr.test-logger'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        implementation "org.slf4j:slf4j-api:$slf4jVersion"
        implementation "com.googlecode.plist:dd-plist:$plistVersion"

        testImplementation(platform "org.junit:junit-bom:$junitVersion")
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}

wrapper {
    gradleVersion = '9.7.1'
    distributionType = Wrapper.DistributionType.ALL
}
