# airplay
airplay.serverName=JavaAirPlay
airplay.width=1920
airplay.height=1080
airplay.fps=30

# player: gstreamer, ffmpeg, vlc, h264-dump
player.implementation=gstreamer
player.tray.enabled=false
player.gstreamer.swing=true

# logs
logging.file.name=java-airplay.log
logging.level.com.github.serezhka=INFO
logging.level.io.netty=INFO
logging.level.org.freedesktop.gstreamer=INFO
